blueprint:
  homeassistant:
    min_version: "2021.1.0"
    name: Temperature Sensor Alarm
    description: "Alarm to notify about temperature changes"
  input:
    temp_sensor:
      type: entity
      description: "Temperature Sensor"
    custom_sensor_name:
      type: string
      description: "Name of the sensor"
    notify_target:
      type: string
      description: "Notification target"
    alarm_1_threshold:
      type: number
      description: "Threshold for Alarm 1"
    alarm_2_threshold:
      type: number
      description: "Threshold for Alarm 2"
  trigger:
    - platform: state
      entity_id: !input temp_sensor
  action:
    - service: notify.notify
      data:
        message: "Alarm triggered!"
        title: "Temperature Alarm"
  mode: single
