blueprint:
  name: Temperature Sensor Alarm
  description: "Alarm to notify about temperature changes"
  domain: automation
  homeassistant:
    min_version: "2021.1.0"
  input:
    temp_sensor:
      name: "Temperature Sensor"
      description: "Temperature Sensor"
      selector:
        entity: {}
    custom_sensor_name:
      name: "Name of the sensor"
      description: "Name of the sensor"
      selector:
        text: {}
    notify_target:
      name: "Notification target"
      description: "Notification target"
      selector:
        text: {}
    alarm_1_threshold:
      name: "Threshold for Alarm 1"
      description: "Threshold for Alarm 1"
      selector:
        number: {}
    alarm_2_threshold:
      name: "Threshold for Alarm 2"
      description: "Threshold for Alarm 2"
      selector:
        number: {}

trigger:
  - platform: state
    entity_id: !input temp_sensor

action:
  - service: notify.send_message
    target:
      entity_id: !input notify_target
    data:
      message: "Alarm triggered!"
      title: "Temperature Alarm"

mode: single
